version: '3'
services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mongo
    environment:
    - ASPNETCORE_ENVIRONMENT=Docker
  mongo:
    container_name: catalogdb
    image: mongo:latest
    ports:
      - "27017:27017"
